# docker compose example
# exposes mocktainer service on port 8081
---
version: '3'
services:
  mocktainer:
    image: docker.io/yesinteractive/mocktainer
    container_name: mocktainer
    restart: always
    ports:
      - "8081:80"